import type { AlertRule, AlertSettings } from '../types/alertRules';

/** 기본 매도 감지 규칙 */
const SELL_RULES: AlertRule[] = [
  {
    id: 'stop-loss',
    name: '기계적 손절',
    description: '보유 수익률이 임계값 이하로 하락',
    severity: 'critical',
    action: 'sell',
    enabled: true,
    filters: ['LOSS_THRESHOLD'],
    filterConfig: { lossThreshold: 5 },
  },
  {
    id: 'overheat-drop',
    name: '과열 후 하락',
    description: 'RSI ≥70 과매수 상태에서 당일 하락 시작',
    severity: 'critical',
    action: 'sell',
    enabled: true,
    filters: ['RSI_OVERBOUGHT', 'DAILY_DROP'],
    filterConfig: {},
  },
  {
    id: 'dead-cross',
    name: '단기 데드크로스',
    description: '단기 이평선이 장기 이평선 하향 돌파',
    severity: 'warning',
    action: 'sell',
    enabled: true,
    filters: ['MA_DEAD_CROSS'],
    filterConfig: { maShortPeriod: 5, maLongPeriod: 20 },
  },
  {
    id: 'trend-break',
    name: '추세 이탈',
    description: '현재가가 이평선 아래 + 손실 중',
    severity: 'warning',
    action: 'sell',
    enabled: true,
    filters: ['PRICE_BELOW_SHORT_MA', 'PROFIT_NEGATIVE'],
    filterConfig: { maShortPeriod: 20 },
  },
  {
    id: 'long-decline',
    name: '장기 하락 확인',
    description: '역배열 + 고점대비 큰 폭 하락',
    severity: 'warning',
    action: 'sell',
    enabled: true,
    filters: ['MA_BEARISH_ALIGN', 'DROP_FROM_HIGH'],
    filterConfig: { maShortPeriod: 20, maLongPeriod: 60, dropFromHighThreshold: 20 },
  },
  {
    id: 'profit-target',
    name: '목표 수익률 도달',
    description: '수익률이 목표치에 도달 — 익절 검토',
    severity: 'warning',
    action: 'sell',
    enabled: true,
    filters: ['PROFIT_TARGET'],
    filterConfig: { profitTargetThreshold: 20 },
  },
  {
    id: 'overheat-profit',
    name: '과열 익절',
    description: '높은 수익률 + RSI 과열진입 — 강한 익절 신호',
    severity: 'critical',
    action: 'sell',
    enabled: true,
    filters: ['PROFIT_TARGET', 'RSI_OVERHEAT_ENTRY'],
    filterConfig: { profitTargetThreshold: 15 },
  },
  {
    id: 'daily-crash',
    name: '급락 경고',
    description: '당일 급격한 하락 — 즉시 점검 필요',
    severity: 'critical',
    action: 'sell',
    enabled: true,
    filters: ['DAILY_CRASH'],
    filterConfig: { dailyCrashThreshold: 5 },
  },
  {
    id: 'strong-sell-signal',
    name: '강력매도 시그널',
    description: '기술적 지표 강력매도 + 거래량 증가 동반',
    severity: 'warning',
    action: 'sell',
    enabled: false,
    filters: ['SIGNAL_STRONG_SELL', 'VOLUME_HIGH'],
    filterConfig: {},
  },
];

/** 기본 매수 기회 규칙 */
const BUY_RULES: AlertRule[] = [
  {
    id: 'pullback',
    name: '눌림목 매수',
    description: '장기MA 위에서 RSI 과매도 — 저점 매수 기회',
    severity: 'info',
    action: 'buy',
    enabled: true,
    filters: ['PRICE_ABOVE_LONG_MA', 'RSI_OVERSOLD'],
    filterConfig: { maLongPeriod: 60 },
  },
  {
    id: 'golden-cross',
    name: '골든크로스',
    description: '단기 이평선이 장기 이평선 상향 돌파',
    severity: 'info',
    action: 'buy',
    enabled: true,
    filters: ['MA_GOLDEN_CROSS'],
    filterConfig: { maShortPeriod: 5, maLongPeriod: 20 },
  },
  {
    id: 'bottom-bounce',
    name: '바닥 반등',
    description: 'RSI 30 이하에서 반등 시작',
    severity: 'info',
    action: 'buy',
    enabled: true,
    filters: ['RSI_BOUNCE'],
    filterConfig: {},
  },
  {
    id: 'volume-confirmed-buy',
    name: '거래량 동반 매수신호',
    description: '강력매수 시그널 + 거래량 급증 — 고확신 매수',
    severity: 'info',
    action: 'buy',
    enabled: true,
    filters: ['SIGNAL_STRONG_BUY', 'VOLUME_SURGE'],
    filterConfig: {},
  },
  {
    id: 'crash-bounce',
    name: '급락 반등 기회',
    description: '급락 후 RSI 반등 + 거래량 동반 — 반등 매수',
    severity: 'info',
    action: 'buy',
    enabled: true,
    filters: ['RSI_BOUNCE', 'VOLUME_HIGH'],
    filterConfig: {},
  },
  {
    id: 'bullish-entry',
    name: '정배열 진입',
    description: '이평선 정배열 + 매수 시그널 — 상승 추세 진입',
    severity: 'info',
    action: 'buy',
    enabled: false,
    filters: ['MA_BULLISH_ALIGN', 'SIGNAL_BUY'],
    filterConfig: { maShortPeriod: 20, maLongPeriod: 60 },
  },
];

export const DEFAULT_ALERT_RULES: AlertRule[] = [...SELL_RULES, ...BUY_RULES];

export const DEFAULT_ALERT_SETTINGS: AlertSettings = {
  rules: DEFAULT_ALERT_RULES,
  enableAutoPopup: true,
};
