// ⚠️ 레거시 아카이브 (v1) — 신규 코드는 import 금지. 전체 마이그레이션용 원본 50개 데이터 보존 전용.
//    정식 시드: constants/knowledgeBase.ts (v2: sources/claims/rules/journal). 마이그레이션 완료 후 삭제 예정.
// 투자 구루 지식 베이스 — 시드 데이터 (Google Drive JSON 으로 병합·동기화될 초기값)
// ---------------------------------------------------------------------------
// 출처: 강환국 강의 전사본 2건 (2026-06-10 "무엇을 언제 사야하나", 2026-06-20 "시장의 마법사 특집")
// 큐레이션 원칙 (사용자 확정):
//   1) 한국 개인투자자가 실행 가능한 durable 규칙만 — 미국 소형주 숏/분봉 EP/시점성 종목콜 제외
//   2) 강환국 = primary(우선 가중), 타 구루 = reference(교차근거 보존)
//   3) STT/OCR 오류 및 사실관계는 웹 교차검증으로 교정 (note/citations 참조)
//   4) 독립검증 불가한 "1.7만 백테스트 수치"는 verification:'unverifiable-claim' + 앱 자체 재백테스트 대상
// 신규 추가/주간 업데이트 시: drafts → 사용자 확인(재질문) → verified 승격 (constants 직접 편집 또는 DB 병합)
// 의존: types/knowledge. 점수/충돌해소: utils/knowledgeScoring.

import type { KnowledgeBase, KnowledgeEntry, KnowledgeSource } from '../types/knowledge.legacy';

const ADDED = '2026-06-21';
const DOC_WHAT_WHEN = '260610_what-when';
const DOC_WIZARDS = '260620_market-wizards';

export const KNOWLEDGE_SOURCES: KnowledgeSource[] = [
  {
    id: DOC_WHAT_WHEN,
    title: '무엇을 언제 사야하나 — 돌파매매 족보 + 1.7만 백테스트',
    date: '2026-06-10',
    type: 'lecture-transcript',
    origin: '강환국 라이브 강의 (자동 전사본)',
    note: 'CANSLIM(오닐)·돌파 계보(리버모어·다바스·와인스타인·미너비니) + 쿨라매기 + 강환국 현대화 버전. STT 오류 다수.',
  },
  {
    id: DOC_WIZARDS,
    title: '시장의 마법사 특집 — 포지션 사이징/손절/심리',
    date: '2026-06-20',
    type: 'lecture-transcript',
    origin: '강환국 라이브 강의 (자동 전사본)',
    note: 'Jack Schwager "Market Wizards" 시리즈(실제 6권+요약본, 2026 신간 The Next Generation 포함). 트레이더명 교정 반영.',
  },
];

export const KNOWLEDGE_ENTRIES: KnowledgeEntry[] = [
  // ── market-regime (언제 매매하는가) ─────────────────────────────────────────
  {
    id: 'absolute-uptrend-only',
    title: '절대적 상승추세에만 투자, 아니면 현금',
    category: 'market-regime',
    statement: '세 조건(①가격 상승 ②가격이 이동평균선 위 ③이동평균선 자체도 상승)을 모두 충족하는 절대적 상승추세 종목에만 투자하고, 아니면 현금을 보유한다.',
    parameters: '강환국 권장 MA 50/200일, 단기 트레이더 10/20일. 조건은 개별주에만 적용(시장지수는 불필요 — 주도주가 시장보다 먼저 움직임).',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'ABSOLUTE_UPTREND', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['추세', '이동평균', '복합신호'],
    note: '앱 보유 지표(MA 5~200 + slopeRatio + 가격-MA 비교)로 복합 플래그 구현 가능.',
  },
  {
    id: 'regime-long-200ma-6m',
    title: '장기 상승장 정의: 200일선 위 6개월 유지',
    category: 'market-regime',
    statement: '가격이 200일선 위에 있고 200일선 위를 6개월 이상 유지했을 때를 장기 추세 상승장으로 본다.',
    parameters: 'price > 200MA AND 200MA 상회 기간 ≥ 6개월',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'REGIME_LONG', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['시장레짐', '200일선'],
  },
  {
    id: 'regime-short-10-20ma',
    title: '단기 신호등: 10일선>20일선 + 둘 다 상승',
    category: 'market-regime',
    statement: '10일선과 20일선이 모두 우상향하고 10일선이 20일선 위에 있을 때만(초록불) 단기 트레이딩한다. 10일선이 20일선 아래로 떨어지면 하락 신호.',
    parameters: '쿨라매기 주장: 이 기준으로 상승추세 약 80% 포착(20% 놓침), 하락추세 80% 회피.',
    guru: 'kullamagi', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'REGIME_SHORT', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://deepvue.com/knowledge-base/qullamaggie-moving-averages/'],
    tags: ['시장레짐', '10일선', '20일선'],
  },
  {
    id: 'bear-market-rest',
    title: '약세장에선 트레이딩 쉬고 자산배분/현금',
    category: 'market-regime',
    statement: '시장 신호등이 빨간불(약세장)이면 돌파/추세 매매를 쉬고 자산배분으로 휴식하며 현금 비중을 확보한다.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['시장레짐', '현금'],
  },
  {
    id: 'allocation-vs-trading-separation',
    title: '자산배분과 트레이딩을 절대 혼용하지 않는다',
    category: 'market-regime',
    statement: '자산배분(정적)은 리밸런싱 날까지 시장 상황과 무관하게 가만히 둔다. 자산배분 종목을 손절/매매하면 더 이상 자산배분이 아니라 트레이딩이며, 보통 그렇게 돈을 잃는다. 1% 룰/손절은 자산배분에 적용하지 않는다.',
    parameters: '강환국 자산의 80~90%가 자산배분, 개별주 트레이딩은 종목당 총자산 1% 미만 베팅.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['자산배분', '리스크관리'],
    note: '강환국 본인도 "여기서 모순이 발생한다"고 인정 — 자산배분은 가만히, 트레이딩은 급등주. 두 계좌를 분리 운용할 것.',
  },
  {
    id: 'lead-sector-leader-no-rotation-bet',
    title: '주도 섹터 우량주 보유, 섹터 로테이션 예측 금지',
    category: 'market-regime',
    statement: '현재 상승하는 주도 섹터의 가장 강한(2류 아닌) 종목을 보유한다. 다음 섹터를 예측해 미리 옮기지 않는다 — 섹터 전환은 RS가 자연히 하락하며 알려주므로 그때 움직여도 늦지 않다.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['섹터', 'RS', '주도주'],
  },

  // ── screening (무엇을 사는가) ──────────────────────────────────────────────
  {
    id: 'rs-90-screening',
    title: '상대강도 RS 90 이상만 매수',
    category: 'screening',
    statement: '여러 종목이 상승추세일 때 종목 선택 기준은 상대강도(RS). RS 90 이하 종목은 아예 고려하지 않는다.',
    parameters: '강환국 종합 RS 가중치: 1개월 40% / 3개월 20% / 6개월 20% / 12개월 20%. RS≥90 = 상위 10%(엘리트).',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'RS_LEADER', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://finance.yahoo.com/news/relative-strength-rating-pinpoints-stocks-214500318.html'],
    tags: ['RS', '상대강도', '스크리닝'],
    note: 'IBD식 RS Rating(1~99)과 동일 개념. 앱 RS 계산식이 백분위 척도인지 검증 필요. 미너비니 트렌드템플릿은 RS≥70을 하한으로 봄(90은 더 엄격한 엘리트 기준).',
  },
  {
    id: 'rs-accelerating',
    title: '이상적 RS: 1개월 RS > 종합 RS, 둘 다 90+',
    category: 'screening',
    statement: 'RS가 지속 상승하는 것이 좋다. 1개월 RS와 종합 RS가 둘 다 90 이상이면서 1개월 RS가 종합 RS보다 높은(가속) 상태가 우량.',
    parameters: '1M RS ≥ 90 AND 종합 RS ≥ 90 AND 1M RS > 종합 RS',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'RS_ACCELERATING', confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['RS', '가속'],
    note: '앱에 1개월 RS 서브메트릭 + 가속 비교 신규 추가 필요.',
  },
  {
    id: 'ma-respect-leader',
    title: '주도주는 핵심 이동평균선을 지지·존중한다',
    category: 'screening',
    statement: '강한 주도주는 하락해도 특정 이평선 아래로 잘 이탈하지 않고 그 선에서 반등(지지)한다. 이 선을 이탈하면 추세 종료로 판단한다.',
    parameters: '핵심 이평선(일봉): 10/20/50/65/200. 주봉: 10주(≈50일)/40주(≈200일). EMA와 SMA 차이는 미미. 예: ROKU는 상승 내내 주봉 10주선 지지.',
    guru: 'weinstein', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'MA_RESPECT', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['이동평균', '지지', '주도주'],
    note: '앱은 65일선·140주선 미보유 — 한국주에서 65일선이 핵심으로 자주 등장하므로 추가 검토. 강환국도 동의.',
  },
  {
    id: 'volume-confirms-advance',
    title: '가격 상승은 거래량 증가를 동반해야 한다',
    category: 'screening',
    statement: '가격 상승은 반드시 거래량 증가(기관 매수 신호)를 동반해야 한다. 어닝/긍정 뉴스와 함께 거래량이 폭발하면 매우 좋은 매수 시그널. 반대로 쉬어가는 조정 구간엔 거래량이 감소해야 정상.',
    parameters: '20일 또는 50일 평균 거래량 대비 최소 +25% 이상. 일봉 1년 최대 거래량 출현도 강한 신호.',
    guru: 'oneil', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'VOLUME_CONFIRMATION', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['거래량', '오닐'],
    note: '앱은 거래량 비율 보유 — "+25% vs 50일평균" 임계값 신규 파라미터화. 강환국도 동일 강조.',
  },
  {
    id: 'high-rs-survivor-bear',
    title: '하락장에서 잘 버틴 고RS 종목을 관찰 후 반등 시 진입',
    category: 'screening',
    statement: '하락·조정장에서 덜 빠지고 잘 버틴 고RS 종목들이 직후 상승장에서 크게 오른다. 하락장엔 거래하지 않더라도 고RS 종목을 예의주시했다가 시장이 상승추세로 전환할 때 진입한다.',
    parameters: '예: 2020 코로나 폭락 때 ZOOM처럼 시장 저점은 낮아지는데 종목 저점은 높아지는 형태.',
    guru: 'generic', guruTier: 'reference', computability: 'advisory',
    confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['RS', '관심종목', '하락장'],
  },
  {
    id: 'pick-among-already-up',
    title: '이미 많이 오른 종목 안에서 고른다 (바닥 예측 금지)',
    category: 'screening',
    statement: '아직 안 오른 종목을 미리 찾는 것은 상위 0.1%도 거의 못한다. 보통 이미 많이 오른 종목이 더 오르므로, 많이 오른(고RS·신고가 근처) 종목 안에서 고른다.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['모멘텀', 'RS'],
  },
  {
    id: 'canslim-framework',
    title: 'CANSLIM — 오닐의 성장주 7대 요소',
    category: 'screening',
    statement: '기관이 사는 성장주를 따라 사는 펀더멘털+기술 프레임워크. C=분기 EPS +25%, A=연 순이익 성장, N=신상품/경영진/신고가, S=작은 시총·적은 주식수, L=업종 리더(상대강도), I=기관 참여 증가, M=시장 방향.',
    parameters: '원서 저자들은 순이익보다 매출 성장을 중시(순이익은 조작 쉬움). 오닐: 주식 4개 중 3개는 시장과 같은 방향 → 하락장에선 수익 어려움.',
    guru: 'oneil', guruTier: 'reference', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://corporatefinanceinstitute.com/resources/equities/can-slim/'],
    tags: ['CANSLIM', '펀더멘털', '오닐'],
  },
  {
    id: 'growth-stock-4-traits',
    title: '고성장주 4대 공통점 (중요도 순)',
    category: 'screening',
    statement: '수백% 상승주의 4대 공통점(중요도 순): ①RS 높고 지속 상승(종합 90+, 1개월 RS 더 높음) ②이평선 지지 후 반등 ③상승 시 거래량 증가/폭발·조정 시 감소 ④갭 상승 동반. 4가지 동시 발생이 매우 긍정적(필수는 아님).',
    parameters: '우선순위: RS(1) > MA지지(2) > 거래량패턴(3) > 갭상승(4)',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['복합', 'RS', '거래량', '갭'],
    note: '가중 복합 점수로 앱에 구현 가능 (RS + MA지지 + 거래량 + 갭).',
  },

  // ── entry-setup (어떤 패턴에서) ────────────────────────────────────────────
  {
    id: 'ma-pullback-entry',
    title: '이평선 눌림목 매수 (강환국 최선호)',
    category: 'entry-setup',
    statement: 'RS 높은 종목이 올랐다가 주춤하며 주요 이평선에 딱 붙을(터치) 때 매수한다. 전통적 돌파보다 일찍·낮게 진입해 손익비가 좋다. 매수 후 이평선 아래로 떨어져 1~2일 회복 못하면 손절.',
    parameters: '기준 이평선 20일 추천(50일도 가능). 매수 시점 = 이평선 살짝 깨는 지점 ~ 이평선 +3% 위. 손절 = 이평선 이탈 후 1~2일 회복 실패 / 전저점.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'MA_PULLBACK_ENTRY', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://qullamaggie.com/my-3-timeless-setups-that-have-made-me-tens-of-millions/'],
    tags: ['눌림목', '이동평균', '진입'],
    note: '강환국이 가장 추천(보기 쉽고 거래기회 빈번). 단 쿨라매기는 눌림목을 비추천하고 돌파만 매수 — 같은 셋업에 대한 두 구루 입장 차이. 강환국 우선 채택.',
  },
  {
    id: 'box-breakout-entry',
    title: '박스권 돌파 매수',
    category: 'entry-setup',
    statement: '강한 상승 후 잠시 쉬어가는 횡보(박스권) 구간을 거쳐 다시 상승하며 이전 고점을 뚫는 시점에 매수한다. 주로 상승장 패턴.',
    parameters: '강환국은 3주 이상 박스권 선호, 쿨라매기는 1~3주 짧은 박스권. 단점: 많은 사람이 따라해 돌파 후 되돌림(실패) 빈번.',
    guru: 'livermore', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'BOX_BREAKOUT', confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://trendspider.com/learning-center/darvas-box-theory-trading-strategy/'],
    tags: ['돌파', '박스권'],
    note: '계보: 리버모어 → 다바스(박스) → 오닐 → 라이언. 앱 breakout/52주고가 신호 활용. "박스권" 정량 정의(기간·변동폭) 필요.',
  },
  {
    id: 'launchpad-then-breakout',
    title: '런치패드(이평선 수렴) 후 돌파 시 매수',
    category: 'entry-setup',
    statement: '주요 이평선들이 좁은 공간에 수렴(밀집)한 뒤 — 런치패드 — 직전 고점/지지선을 돌파할 때 진입한다. 주로 하락/장기횡보 후 반전 패턴.',
    parameters: '수렴 이평선 예: 10/21/50/65/200. 매수 시점 = 수렴 후 전고점 돌파. 수렴만으로는 매수 금지(별도 항목).',
    guru: 'kullamagi', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'LAUNCHPAD_BREAKOUT', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://deepvue.com/indicators/launch-pad-the-early-entry-technique/'],
    tags: ['런치패드', '이동평균', '수렴', '돌파'],
    note: '"런치패드/원기옥"은 쿨라매기/미너비니가 만든 용어가 아니라 커뮤니티·벤더(Deepvue·TradingView) 통칭. 미너비니 VCP·쿨라매기 "이평선 서핑"과 같은 계열. 앱에 MA 수렴폭(밴드폭 %) 지표 신규 필요.',
  },
  {
    id: 'ma-reclaim-entry',
    title: '이평선 재돌파(복귀) 매수',
    category: 'entry-setup',
    statement: '주가가 이평선 아래로 떨어졌다가 다시 그 위로 복귀하는 시점에 매수한다. 다시 아래로 떨어지면 손절. 크게 한 번 오른 뒤 몇 주 이상 횡보하는 종목에서 자주 발생.',
    parameters: '기준 이평선 20일 추천. 손절 포인트 = 전저점.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'MA_RECLAIM', confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['이동평균', '재돌파', '눌림목'],
  },

  // ── entry-timing (정확히 언제) ─────────────────────────────────────────────
  {
    id: 'all-time-high-breakout',
    title: '역대/장기 신고가 돌파 = 매수 신호',
    category: 'entry-timing',
    statement: '역대 최고가 또는 장기(예 5년) 최고가 돌파는 늘 긍정적 매수 신호다. 위에 물린 투자자가 없어 매물 부담(저항)이 없기 때문. 단 돌파 다음날 시가가 큰 갭 상승이면 진입 보류.',
    parameters: '신고가 돌파 + 거래량 동반. 5년 최고가도 역대 최고가에 준함.',
    guru: 'darvas', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'ALL_TIME_HIGH_BREAKOUT', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['신고가', '돌파'],
    note: '앱은 52주 신고가 보유 — 역대/5년 최고가는 더 긴 룩백 신규 필요.',
  },
  {
    id: 'gap-up-first-second',
    title: '첫 1~2회 갭상승에 매수, 3회+ 잦은 갭은 과열 경고',
    category: 'entry-timing',
    statement: '200~500% 상승주는 대개 여러 차례 갭상승을 동반한다. 첫 번째·두 번째 갭상승 시점이 유리한 매수 타이밍(기관 공격 매수). 단 갭이 너무 잦으면(처음 한두 번 이후) 에너지 소진으로 오히려 고점 매도 신호.',
    parameters: '1·2차 갭업 = 매수 / 3차+ 잦은 갭 = 고점 경고',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'GAP_UP', confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['갭', '진입'],
    note: '앱에 갭 감지(시가 vs 전일종가) 신규 필요. 과열 케이스는 기존 climax-top과 연계.',
  },
  {
    id: 'launchpad-needs-breakout',
    title: '런치패드 단독 매수 금지 — 반드시 돌파 확인',
    category: 'entry-timing',
    statement: '이평선 5개가 수렴(런치패드/원기옥)했다고 즉시 매수하면 안 된다. 런치패드는 하락추세에서도 나타나기 때문. 반드시 형성 후 강한 돌파가 확인될 때 진입한다.',
    parameters: '예: 인텔은 원기옥 후 돌파 없이 55→25불 추락. 수렴+돌파 효과도 항상은 아님(횡보 사례 존재).',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['런치패드', '돌파', '주의'],
  },
  {
    id: 'avoid-extended-chase',
    title: '이격도 과대 시 추격매수 금지',
    category: 'entry-timing',
    statement: '돌파 후 너무 올라 주가가 10일/20일 이평선보다 한참 위(이격 심함)이면 추격매수 금지. 진정되어 이평선에 근접하면 다시 매수 고려.',
    parameters: '예: 10일선 대비 +8% 이상이면 과열로 보고 진입 보류 → 10일선 회귀 시 진입.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'PRICE_EXTENDED', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['이격도', '과열', '주의'],
    note: '앱에 (가격-MA)/MA % 이격도 지표 신규 필요(기존 MA로 파생 가능).',
  },
  {
    id: 'late-entry-within-5pct',
    title: '돌파 놓쳐도 5% 이내면 지각 진입 허용',
    category: 'entry-timing',
    statement: '첫 돌파 타이밍을 놓쳤어도 돌파 지점 대비 +5% 미만이면 당일 종가나 다음날 진입해도 된다(직장인 현실 고려).',
    parameters: '돌파 100 → 현재 103(+3%) 진입 OK, 110(+10%) 포기.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'author-opinion', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['진입', '실전'],
  },
  {
    id: 'rsi-not-standalone',
    title: 'RSI 단독으로 매수/매도 판단 금지',
    category: 'entry-timing',
    statement: 'RSI가 높다고 무조건 매수해서는 안 되고(상승 중이면 당연히 높음), RSI 낮다고 추세 꺾인 종목을 사도 안 된다. RSI는 보조 지표이며 차트·추세를 함께 봐야 한다.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['RSI', '주의'],
    note: '앱 RSI(14) 신호에 "보조 지표" 캐비엇 표기.',
  },

  // ── exit-stoploss (손절) ───────────────────────────────────────────────────
  {
    id: 'stop-mandatory-7-15',
    title: '손절 필수, 폭 7~15%',
    category: 'exit-stoploss',
    statement: '손절은 필수(아예 안 하는 것 금지). 손절폭은 7~15% 범위에서 유연하게 설정한다. 7% 미만은 너무 빨리 잘려 결과가 나빴다.',
    parameters: '7% ≤ 손절 ≤ 15%. 7% 손절 평균 보유 2.5개월(기회비용↓) vs 15% 손절 4개월(수익률 다소↑).',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'STOP_LOSS_PCT', confidence: 'strong', verification: 'unverifiable-claim',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['손절', '백테스트'],
    note: '"강환국+Claude 1.7만 백테스트" 결론 — 데이터셋/방법론 비공개, 1.7만 중 최적 선택은 과적합 위험. 방향성(비대칭 손익비)은 공개 근거와 부합. 앱 자체 재백테스트로 검증 예정.',
  },
  {
    id: 'stop-on-entry-order',
    title: '매수와 동시에 손절 주문을 건다',
    category: 'exit-stoploss',
    statement: '감정 개입을 차단하기 위해 매수 시 손절(스톱) 주문을 함께 건다. 손절은 재능이 아니라 규칙이다.',
    guru: 'generic', guruTier: 'reference', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['손절', '규칙', '심리'],
    note: '시장의 마법사 9인 공통. 강환국도 강조.',
  },
  {
    id: 'stop-50ma-2day-break',
    title: '50일선 2일 연속 이탈 시 청산',
    category: 'exit-stoploss',
    statement: '50일선 아래로 2일 연속 이탈하면 가격 수준과 무관하게 매도한다(손절·익절 공통). 보수적 투자자는 이평선 이탈 후 1~2일 회복 실패 시 매도. 5일/20일선 이탈도 사용 가능(거래 더 잦음).',
    parameters: '기본 50일선 2일 연속 이탈. 와인스타인식은 150일선(30주선) 이탈.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'MA_EXIT_50', confidence: 'strong', verification: 'unverifiable-claim',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['손절', '이동평균', '청산'],
    note: '이평선 이탈 청산 개념 자체는 와인스타인 등으로 확립됨(verified 수준). 단 "50일선 2일 연속"이라는 구체 파라미터는 1.7만 백테스트 산출 → unverifiable-claim, 앱 재백테스트 대상.',
  },
  {
    id: 'stop-volatility-based',
    title: '변동성에 따라 손절폭 차등 (주식 타이트, 코인 넓게)',
    category: 'exit-stoploss',
    statement: '자산 변동성에 따라 손절폭을 다르게 설정한다 — 저변동성 주식은 타이트하게, 고변동성 코인은 넓게.',
    parameters: '저변동성 주식 5%, 일반 주식 4~8%, 코인 20%. 1% 룰과 결합해 포지션 역산.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['손절', '변동성', 'ATR'],
    note: '앱 ATR(14)로 변동성 기반 손절폭 자동 제안 가능.',
  },
  {
    id: 'no-averaging-down',
    title: '물타기(평단 낮추기) 절대 금지',
    category: 'exit-stoploss',
    statement: '내려가는 손실 종목에 추가 매수(물타기)는 절대 금지. "손절하지 않으면 파산은 마느냐가 아니라 언제냐의 문제"(루소).',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://www.turtletrader.com/average-up/'],
    tags: ['물타기', '리스크관리', '심리'],
    note: '트레이딩 한정 규칙(장기 가치투자/적립식 DCA는 예외). 앱에서 손실 종목 추가매수 시 경고 가능.',
  },
  {
    id: 'weinstein-150ma-exit',
    title: '와인스타인 150일선(30주선) 이탈 매도',
    category: 'exit-stoploss',
    statement: '와인스타인 스테이지 분석의 대표 매도 기준: 주가가 (평평해지거나 하락하는) 30주선=150일선 아래로 확실히 이탈하면 매도(스테이지 3→4 전환).',
    parameters: '30주 SMA ≈ 150일선. 와인스타인 본인은 기관이 더 보는 200일선을 현대적 대체로 사용.',
    guru: 'weinstein', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'weinstein-150-break', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://traderlion.com/trading-strategies/stage-analysis/'],
    tags: ['와인스타인', '150일선', '매도'],
    note: '앱에 이미 weinstein-150-break 신호 존재 — 본 항목이 그 출처/근거.',
  },

  // ── exit-profit (익절) ─────────────────────────────────────────────────────
  {
    id: 'profit-4x-stop-half',
    title: '손절폭의 4배 도달 시 절반 익절',
    category: 'exit-profit',
    statement: '익절은 손절폭의 4배 수익 도달 시 절반 매도(기존 2~3배보다 4배가 우수). 나머지 절반은 50일선 이탈할 때까지 보유.',
    parameters: '익절 목표 = 4 × 손절폭. 예: 손절 10% → +40%에서 절반, 손절 7% → +28%에서 절반.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'PROFIT_TARGET_4X', confidence: 'strong', verification: 'unverifiable-claim',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['익절', '백테스트'],
    note: '1.7만 백테스트 산출 수치 — 비대칭 손익비 원칙은 추세추종 문헌과 부합하나 "정확히 4배"는 과적합 위험. 앱 재백테스트 대상.',
  },
  {
    id: 'trailing-50ma-remainder',
    title: '잔여 절반은 50일선 이탈까지 보유(트레일링)',
    category: 'exit-profit',
    statement: '4배 익절로 절반을 판 뒤, 나머지 절반은 50일선을 이탈할 때 매도해 추세를 끝까지 탄다. 매도 기준선은 20일선도 가능(거래 더 잦음).',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'MA_EXIT_50', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['익절', '트레일링', '50일선'],
    note: 'stop-50ma-2day-break와 같은 신호키(MA_EXIT_50) 공유 — 손절/익절 양쪽에서 트리거.',
  },
  {
    id: 'time-stop-6m',
    title: '타임스톱: 6개월(120일) 미충족 시 매도',
    category: 'exit-profit',
    statement: '익절(4배 절반)·이평선 이탈·손절 세 조건 중 어느 것도 6개월(약 120거래일) 내 충족 안 되면 손익 무관 매도한다. 모멘텀 상실로 보고 "반려주식"(장기 방치)을 방지.',
    parameters: '타임스톱 = 6개월 ≈ 120거래일',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'signal',
    mappedSignalKey: 'TIME_STOP', confidence: 'strong', verification: 'unverifiable-claim',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['타임스톱', '기회비용', '백테스트'],
    note: '보유기간 타이머(포지션별) 신규 필요. 1.7만 백테스트 산출.',
  },
  {
    id: 'breakeven-stop-after-partial',
    title: '절반 익절 후 잔여 손절가를 본전으로 상향',
    category: 'exit-profit',
    statement: '강한 움직임(보통 3~5일) 후 절반을 익절하고, 나머지 절반의 손절가를 매수가(본전)로 올려 해당 거래를 무손실로 만든다.',
    guru: 'kullamagi', guruTier: 'reference', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['익절', '본전스톱', '쿨라매기'],
  },
  {
    id: 'climax-top-sell',
    title: '클라이맥스 톱(과열) 매도 신호',
    category: 'exit-profit',
    statement: '상승 막바지 과열 특징(거래량 폭발, 급각도 상승, 다중 갭, 이평선 대비 이격 과대, 추세채널 고점 초과)이 보이면 매수 금지·보유 시 매도 고려.',
    parameters: '급각도 + 거래량 폭발 + 다중 갭 + 이격 과대 + 채널 고점 초과. RSI 높음은 보조(단독 금지).',
    guru: 'minervini', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'climax-top', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['클라이맥스', '과열', '매도'],
    note: '앱에 이미 climax-top 신호 존재 — 본 항목이 구성요소 정의/근거. 강환국·와인스타인·미너비니 공통.',
  },
  {
    id: 'distribution-sell',
    title: '디스트리뷰션(매물 출회) 경고',
    category: 'exit-profit',
    statement: '거래량은 터졌는데 가격은 못 오르는(고거래량 하락) 날이 군집하면 큰손이 물량을 던지는 중 — 매도 압력 경고.',
    parameters: 'O\'Neil: 약 4주 내 4~5일 디스트리뷰션데이 군집 = 시장 고점 경고. 지수 5%↑ 반등 또는 25거래일 후 만료.',
    guru: 'oneil', guruTier: 'reference', computability: 'signal',
    mappedSignalKey: 'distribution-high', confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://www.williamoneil.com/tag/distribution-day/'],
    tags: ['디스트리뷰션', '거래량', '매도'],
    note: '앱에 이미 distribution-high 신호 + 시장 디스트리뷰션 배너 존재 — 본 항목이 근거.',
  },

  // ── position-sizing (얼마나 사는가) ────────────────────────────────────────
  {
    id: 'risk-1pct-per-trade',
    title: '거래당 손실 한도 = 총자산 1% (최대 2%)',
    category: 'position-sizing',
    statement: '한 번의 거래로 총자산의 1%(최대 2%)만 잃도록 포지션을 설계한다. 1% 손실로 20번 연속 실패해도 자산 80% 이상 보존. 위대한 트레이더 대부분은 전략이 아니라 과도한 베팅으로 파산했다.',
    parameters: '거래당 리스크 = 자산의 1%(보수) ~ 2%(최대). 강환국 본인은 개별주에서 1% 미만. 자산배분에는 미적용.',
    guru: 'generic', guruTier: 'reference', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    citations: ['https://vantharpinstitute.com/van-tharp-teaches-position-sizing-strategies-and-risk-management/'],
    tags: ['포지션사이징', '1%룰', '리스크관리'],
    note: 'Van Tharp·Larry Hite("never risk >1%") 등 교과서 표준. 9인 트레이더 전원 준수. 앱에 포지션 사이징 계산기 신규 필요.',
  },
  {
    id: 'position-size-from-stop',
    title: '포지션 크기는 손절폭에서 역산한다',
    category: 'position-sizing',
    statement: '베팅 금액은 주관적 확신이 아니라 손절폭과 리스크 한도에서 역산한다: 포지션 = (자산 × 리스크%) / 손절폭%.',
    parameters: '예(자산 1억, 리스크 1% = 100만): 손절 8% → 1,250만 / 손절 5% → 2,000만 / 손절 4% → 2,500만 / 코인 손절 20% → 500만. 산수 검증 완료.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    citations: ['https://www.cmegroup.com/education/courses/trade-and-risk-management/the-2-percent-rule'],
    tags: ['포지션사이징', '손절', '계산기'],
  },
  {
    id: 'max-3-4-positions',
    title: '동시 보유 종목 3~4개로 제한',
    category: 'position-sizing',
    statement: '한 종목 10% 투입 기준 최대 동시 보유는 3~4개. 더 늘리려면 종목당 금액을 줄인다. 한 종목 비중 과다(50~100%)는 망하는 가장 빠른 길.',
    parameters: '동시 3~4종목. 비중 확대는 주가 상승 시 추가매수로만(물타기 금지).',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['집중도', '분산'],
    note: '앱에 포지션 수/집중도 체크 신규 가능.',
  },
  {
    id: 'pyramiding-on-strength-only',
    title: '추가매수(피라미딩)는 상승 시에만',
    category: 'position-sizing',
    statement: '1차 매수 후 주가가 상승해 돌파를 갱신할 때마다 2·3·4차 추가매수(불타기)한다. 하락 시 추가매수(물타기)는 절대 금지. 1차 후 7% 빠지면 2차 매수 안 함.',
    parameters: '미너비니·데이브 라이언: 불타기해도 한 종목 총자산 약 25% 이내로 제한.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['피라미딩', '불타기', '추가매수'],
    note: '불타기는 강세장에서 기본기를 수천 거래로 완성한 뒤 마지막에 배우는 고난도 기술(프롤리히) — 초보 비권장.',
  },

  // ── psychology (심리·행동·메타) ────────────────────────────────────────────
  {
    id: 'plan-exit-before-entry',
    title: '매수 전에 매도(손절·익절) 시점을 먼저 정한다',
    category: 'psychology',
    statement: '주식을 사기 전에 언제 팔지(손절·익절)를 먼저 정한다. 셋업의 진짜 의미는 손실을 짧게 제한하고 수익을 크게 가져가는 것.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    tags: ['계획', '손절', '익절'],
    note: '앱: 매수 기록 시 손절가/목표가 입력 유도 가능.',
  },
  {
    id: 'low-winrate-high-payoff',
    title: '낮은 승률 + 높은 손익비로 수익 (3할 타자론)',
    category: 'psychology',
    statement: '승률이 50% 이하여도(셋업 전략 승률 40% 미만, 쿨라매기 25~30%) 손익비가 2 이상이면 수익. 야구 3할 타자처럼 대부분 실패해도 이기는 거래에서 크게 벌면 된다. 손절을 두려워 말 것.',
    parameters: '전략 승률 <40%, 손익비 ≥2. 단 손익비 2:1의 손익분기 승률은 약 33% — 승률이 그 아래면 손실.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WHAT_WHEN, sourceDate: '2026-06-10', addedDate: ADDED,
    citations: ['https://tradethatswing.com/win-rate-risk-reward-and-finding-the-profitable-balance/'],
    tags: ['승률', '손익비', '기대값'],
    note: '교정: "승률<40%면 수익"은 손익분기 승률(2:1 기준 ~33.3%) 위에서만 참. 앱이 실현 승률/손익비 추적 가능.',
  },
  {
    id: 'profit-target-danger',
    title: '수익 목표는 위험하다 — 잘 벌 때 가장 조심',
    category: 'psychology',
    statement: '연간 수익 목표는 위험하다. 잘 벌 때(자만할 때)가 규칙을 가장 많이 어기는 시기다. 대형 수익 직후엔 오히려 포지션을 줄이고 더 조심해야 한다.',
    guru: 'generic', guruTier: 'reference', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['심리', '자만', '리스크관리'],
    note: '브라이트스타인·쿨라매기 사례 — 목표 조기달성 후 오버베팅으로 큰 손실. 시장의 마법사 핵심 테마.',
  },
  {
    id: 'weekly-review-journal',
    title: '거래를 기록하고 매주 복기한다 (트레이딩 저널)',
    category: 'psychology',
    statement: '모든 거래를 기록/녹화하고 정기적으로(매주) 복기한다. 매수·매도 직후 즉시 논리와 근거를 메모해 기억 왜곡을 막는다. 실수를 줄여나가는 과정이 곧 고수가 되는 길.',
    parameters: '브라이트스타인: 10년간 매주 일요일 거래영상 2배속 복기. 돈깡(강민우)도 어릴 때부터 복기 습관.',
    guru: 'breitstein', guruTier: 'reference', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['복기', '저널', '심리'],
    note: '앱에 매수/매도 사유 기록 + 주간 복기 뷰 신규 가능. (이름 교정: 브라이트스타인=Lance Breitstein)',
  },
  {
    id: 'focus-1-2-strategies',
    title: '본인 성격에 맞는 1~2개 전략에 집중·숙달',
    category: 'psychology',
    statement: '모든 전략을 잘할 수 없으니 본인 성격에 맞는 1~2개 전략에 집중·숙달한다. 차용하더라도 직접 백테스트로 검증해 본인 것으로 만든다("100명 가르쳐도 1명만 성공").',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'strong', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['메타', '전략집중'],
  },
  {
    id: 'min-sample-30-40',
    title: '백테스트 유의미 최소 표본 30~40회',
    category: 'psychology',
    statement: '이평선 터치 등 시그널 통계가 유의미하려면 최소 30~40회(이상적으로 수십 회 이상)의 발생 표본이 필요하다. 4회는 무의미.',
    parameters: '최소 30~40회 이벤트.',
    guru: 'kang-hwanguk', guruTier: 'primary', computability: 'advisory',
    confidence: 'qualified', verification: 'verified',
    sourceDoc: DOC_WIZARDS, sourceDate: '2026-06-20', addedDate: ADDED,
    tags: ['백테스트', '통계신뢰도'],
    note: '앱이 종목별 시그널 통계를 낼 때 표본 임계값 가드로 사용.',
  },
];

export const SEED_KNOWLEDGE_BASE: KnowledgeBase = {
  version: 1,
  entries: KNOWLEDGE_ENTRIES,
  sources: KNOWLEDGE_SOURCES,
  lastUpdated: ADDED,
};
